name: Docker Size Annotation
description: Annotates the build with a docker image size
author: https://github.com/envato/docker-size-annotation-buildkite-plugin
requirements:
  - docker
configuration:
  properties:
    annotate:
      type: [string, array]
      minimum: 1
  additionalProperties: false
