#!/bin/bash
set -euo pipefail


function plugin_read_list() {
  prefix_read_list "BUILDKITE_PLUGIN_DOCKER_SIZE_ANNOTATION_$1"
}

function prefix_read_list() {
  local prefix="$1"
  local parameter="${prefix}_0"

  if [[ -n "${!parameter:-}" ]]; then
    local i=0
    local parameter="${prefix}_${i}"
    while [[ -n "${!parameter:-}" ]]; do
      echo "${!parameter}"
      i=$((i+1))
      parameter="${prefix}_${i}"
    done
  elif [[ -n "${!prefix:-}" ]]; then
    echo "${!prefix}"
  fi
}

function docker_compose_project_name() {
  echo "buildkite${BUILDKITE_JOB_ID//-}"
}

if [[ -n "$(plugin_read_list ANNOTATE)" ]]; then
  for image in $(plugin_read_list ANNOTATE); do
    tag="$(docker_compose_project_name)-${image}"
    context="image_size_${tag}"
    echo "Using tag: ${tag} and context: ${context}"
    message=$(docker images --format "**${BUILDKITE_LABEL}** - *${image}* docker image is **{{.Size}}** (Tag {{.Tag}} ID {{.ID}})" "$tag")
    echo "${message:-Unknown}" | buildkite-agent annotate --style info --context "${context}"
  done
fi
